[bookmark]

[jwt]
  secret = "123456789123456789"

[server]
  address = ":8082"
  dumpRouterMap = false
  debug = false

[logger]
  level = "info"

[database.logger]
  level = "all"
  stdout = true

[database.default]
  debug = true
  timezone = "Asia/Shanghai"
  # link = "mysql:root:root@tcp(127.0.0.1:3306)/db?charset=utf8mb4&parseTime=True&loc=Local"
  link = "sqlite::@file(./bookmark.sqlite3)"
